FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_BASE_URL=http://localhost:3000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
EXPOSE 5173
CMD [ "npm", "run", "dev", "--", "--host" ]
